version: '3.8'

services:
  app:
    image: node:16-alpine
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - '5051:80'

    # command: sh -c "npm i && npm run dev -- -p 80"
    command: sh -c "npm i && npm run build && npm start -- -p 80"
