version: '3.8'

services:
  app:
    image: node:16-alpine
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - '5051:3000'

    command: sh -c "yarn i && yarn run dev"
