name: Deploy NextJS App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build New Docker Image, Delete Old One & Deploy Changes
    runs-on: self-hosted
    env:
      OLD_IMAGE: default
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "OLD_IMAGE=$(docker images --format="{{.Repository}} {{.ID}}" |
          grep "^mhm13dev " | 
          cut -d' ' -f2)" >> $GITHUB_ENV
      - run: docker build -t mhm13dev .
      - run: docker-compose -f ./docker-compose-prod.yml up -d
      - run: docker image rm $OLD_IMAGE
