name: Deploy NextJS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - run: docker-compose down
      - run: docker-compose -f ./docker-compose-prod.yml up -d
