name: Deploy NextJS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - run: |
          OLD_IMAGE=$(docker images --format="{{.Repository}} {{.ID}}" |
          grep "^mhm13dev " |
          cut -d' ' -f2)
      - run: docker build -t mhm13dev .
      - run: docker-compose -f ./docker-compose-prod.yml up -d
      - run: docker image rm $OLD_IMAGE
